services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-mnemonic
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mnemonic-network

volumes:
  pgdata:

networks:
  mnemonic-network:
    driver: bridge